// --- Translations ---
const translations = {
    "en": { "page_title": "Caddy Traffic Dashboard", "main_title": "Caddy Traffic", "subtitle": "Real-time Monitoring Dashboard", "total_requests": "Total Requests", "total_websockets": "WebSocket Connects", "transport": "Transport", "tls_version": "TLS Version", "cipher_suites": "Cipher Suites", "curves": "Key Exchange (Curves)", "alpn": "ALPN (Negotiated)", "hsts_status": "HSTS Status", "ip_version": "IP Version", "http_protocols": "HTTP Protocols", "response_codes": "Response Codes", "no_data": "No data", "footer": "Generated by Caddy Traffic Stats Module", "loading": "Loading..." },
    "zh-CN": { "page_title": "Caddy 流量监控看板", "main_title": "Caddy 流量监控", "subtitle": "实时流量监控面板", "total_requests": "总请求数", "total_websockets": "WebSocket 连接数", "transport": "传输层协议", "tls_version": "TLS 版本", "cipher_suites": "加密套件 (Cipher Suites)", "curves": "密钥交换 (Curves)", "alpn": "应用层协商 (ALPN)", "hsts_status": "HSTS 状态", "ip_version": "IP 版本", "http_protocols": "HTTP 协议", "response_codes": "响应状态码", "no_data": "暂无数据", "footer": "由 Caddy Traffic Stats 模块生成", "loading": "加载中..." },
    "zh-TW": { "page_title": "Caddy 流量監控看板", "main_title": "Caddy 流量監控", "subtitle": "即時流量監控面板", "total_requests": "總請求數", "total_websockets": "WebSocket 連線數", "transport": "傳輸層協議", "tls_version": "TLS 版本", "cipher_suites": "加密套件 (Cipher Suites)", "curves": "密鑰交換 (Curves)", "alpn": "應用層協商 (ALPN)", "hsts_status": "HSTS 狀態", "ip_version": "IP 版本", "http_protocols": "HTTP 協議", "response_codes": "響應狀態碼", "no_data": "暫無數據", "footer": "由 Caddy Traffic Stats 模組生成", "loading": "載入中..." },
    "ja": { "page_title": "Caddy トラフィック監視", "main_title": "Caddy トラフィック", "subtitle": "リアルタイム監視ダッシュボード", "total_requests": "総リクエスト数", "total_websockets": "WebSocket 接続数", "transport": "トランスポート層", "tls_version": "TLS バージョン", "cipher_suites": "暗号スイート", "curves": "鍵交換 (Curves)", "alpn": "ALPN (交渉済み)", "hsts_status": "HSTS ステータス", "ip_version": "IP バージョン", "http_protocols": "HTTP プロトコル", "response_codes": "レスポンスコード", "no_data": "データなし", "footer": "Caddy Traffic Stats モジュールによって生成", "loading": "読み込み中..." }
};

const langLabels = { "en": "English", "zh-CN": "简体中文", "zh-TW": "繁體中文", "ja": "日本語" };
let currentLang = 'en';
let dashboardConfig = null;
let currentStats = null;
const colorPalette = ['--palette-1', '--palette-2', '--palette-3', '--palette-4', '--palette-5', '--palette-6', '--palette-7', '--palette-8'];

// --- Spotlight Effect Logic (New) ---
// 监听鼠标移动，更新所有卡片的 CSS 变量
document.addEventListener("mousemove", (e) => {
    const cards = document.getElementsByClassName("card");
    for (const card of cards) {
        const rect = card.getBoundingClientRect();
        const x = e.clientX - rect.left;
        const y = e.clientY - rect.top;
        card.style.setProperty("--mouse-x", `${x}px`);
        card.style.setProperty("--mouse-y", `${y}px`);
    }
});

// --- Language UI Logic ---
function toggleLangMenu() {
    document.getElementById('langMenu').classList.toggle('open');
    document.getElementById('langBtn').classList.toggle('active');
}

function selectLanguage(lang) {
    changeLanguage(lang);
    document.getElementById('langMenu').classList.remove('open');
    document.getElementById('langBtn').classList.remove('active');
}

document.addEventListener('click', function(event) {
    if (!document.querySelector('.lang-container').contains(event.target)) {
        document.getElementById('langMenu').classList.remove('open');
        document.getElementById('langBtn').classList.remove('active');
    }
});

// --- Auth & Init Logic ---
async function initDashboard() {
    detectLanguage();
    try {
        const configRes = await fetch('./discovery');
        if (configRes.status === 401) {
            showLoginModal();
            return;
        }
        if (!configRes.ok) throw new Error("Failed to fetch config");
        dashboardConfig = await configRes.json();
        
        renderScopeBadge(dashboardConfig.scope);
        buildLayout(dashboardConfig.layout);
        applyTranslations();
        fetchData();
        setInterval(fetchData, 60000);
    } catch (err) { console.warn("Init error:", err); }
}

function showLoginModal() {
    document.getElementById('loginModal').classList.add('active');
    document.getElementById('loadingState').innerText = "Authentication required";
}

async function handleLogin(e) {
    e.preventDefault();
    const password = document.getElementById('passwordInput').value;
    const errorMsg = document.getElementById('loginError');
    try {
        const res = await fetch('./login', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ password: password })
        });
        if (res.ok) {
            document.getElementById('loginModal').classList.remove('active');
            errorMsg.style.display = 'none';
            initDashboard();
        } else {
            errorMsg.style.display = 'block';
            errorMsg.innerText = "Incorrect password";
            const card = document.querySelector('.login-card');
            card.style.transform = 'translateX(10px)';
            setTimeout(() => card.style.transform = '', 100);
        }
    } catch (err) {
        errorMsg.style.display = 'block';
        errorMsg.innerText = "Connection failed";
    }
}

async function fetchData() {
    try {
        const res = await fetch('./data');
        if (res.status === 401) { showLoginModal(); return; }
        if (!res.ok) return;
        currentStats = await res.json();
        updateDashboardValues();
    } catch (e) { console.warn("Fetch data failed", e); }
}

// --- UI Construction ---
function renderScopeBadge(scope) {
    const badge = document.getElementById('scopeBadge');
    badge.style.display = 'inline-block';
    badge.className = `badge ${scope === 'global' ? 'badge-global' : 'badge-instance'}`;
    badge.innerText = scope.charAt(0).toUpperCase() + scope.slice(1);
}

function buildLayout(layoutItems) {
    const container = document.getElementById('dashboardContent');
    container.innerHTML = ''; 
    layoutItems.forEach((item, index) => {
        const cardWrapper = document.createElement('div');
        cardWrapper.className = `card ${item.grid_width === 'half' ? 'col-half' : 'col-full'}`;
        cardWrapper.style.animationDelay = `${index * 0.1}s`;
        if (item.type === 'metric') {
            cardWrapper.innerHTML = `
                <div class="metric-group">
                    <div class="metric-value" id="val-${item.id}">0</div>
                    <div class="metric-label" data-i18n="${item.title_key}"></div>
                </div>`;
        } else if (item.type === 'chart') {
            cardWrapper.innerHTML = `
                <div class="card-title" data-i18n="${item.title_key}"></div>
                <div id="list-${item.id}" class="stats-list">
                    <div class="empty-state" data-i18n="loading"></div>
                </div>`;
        }
        container.appendChild(cardWrapper);
    });
}

function updateDashboardValues() {
    if (!dashboardConfig || !currentStats) return;
    dashboardConfig.layout.forEach(item => {
        const dataValue = currentStats[item.data_key];
        if (item.type === 'metric') animateNumber(`val-${item.id}`, dataValue || 0);
        else if (item.type === 'chart') renderChartList(`list-${item.id}`, dataValue, item);
    });
}

function renderChartList(containerId, dataMap, configItem) {
    const container = document.getElementById(containerId);
    if (!container) return;
    if (!dataMap || Object.keys(dataMap).length === 0) {
        const noDataText = translations[currentLang] ? translations[currentLang].no_data : "No data";
        container.innerHTML = `<div class="empty-state">${noDataText}</div>`;
        return;
    }
    const fragment = document.createDocumentFragment();
    const total = Object.values(dataMap).reduce((a, b) => a + b, 0);
    const keys = Object.keys(dataMap).sort((a, b) => dataMap[b] - dataMap[a]);
    keys.forEach((key, index) => {
        const count = dataMap[key];
        const percentage = total > 0 ? ((count / total) * 100).toFixed(1) : 0;
        let colorVar;
        if (configItem.color_mode === 'status_code') {
            if (key.startsWith('2')) colorVar = 'var(--color-2xx)';
            else if (key.startsWith('3')) colorVar = 'var(--color-3xx)';
            else if (key.startsWith('4')) colorVar = 'var(--color-4xx)';
            else if (key.startsWith('5')) colorVar = 'var(--color-5xx)';
            else { const paletteColor = colorPalette[index % colorPalette.length]; colorVar = `var(${paletteColor})`; }
        } else {
            const paletteColor = colorPalette[index % colorPalette.length];
            colorVar = `var(${paletteColor})`;
        }
        const itemDiv = document.createElement('div');
        itemDiv.className = 'stat-item';
        itemDiv.innerHTML = `
            <div class="stat-header"><span class="stat-name">${key}</span><span>${count.toLocaleString()} <span style="opacity:0.5;font-size:0.85em;margin-left:4px">(${percentage}%)</span></span></div>
            <div class="progress-track"><div class="progress-bar" style="background-color: ${colorVar}; width: ${percentage}%"></div></div>`;
        fragment.appendChild(itemDiv);
    });
    container.innerHTML = '';
    container.appendChild(fragment);
}

function animateNumber(elementId, endValue) {
    const el = document.getElementById(elementId);
    if (!el) return;
    const current = parseInt(el.innerText.replace(/,/g, '')) || 0;
    if (current === endValue) return;
    const duration = 1000;
    const startTime = performance.now();
    function update(currentTime) {
        const elapsed = currentTime - startTime;
        const progress = Math.min(elapsed / duration, 1);
        const ease = 1 - Math.pow(1 - progress, 4);
        const val = Math.floor(current + (endValue - current) * ease);
        el.innerText = val.toLocaleString();
        if (progress < 1) requestAnimationFrame(update);
        else el.innerText = endValue.toLocaleString();
    }
    requestAnimationFrame(update);
}

// --- i18n Logic ---
function detectLanguage() {
    const storedLang = localStorage.getItem('caddy_stats_lang');
    if (storedLang && translations[storedLang]) { currentLang = storedLang; }
    else {
        const browserLang = navigator.language || navigator.userLanguage;
        if (browserLang.toLowerCase().includes('zh-cn')) currentLang = 'zh-CN';
        else if (browserLang.toLowerCase().includes('zh-tw') || browserLang.toLowerCase().includes('zh-hk')) currentLang = 'zh-TW';
        else if (browserLang.toLowerCase().includes('ja')) currentLang = 'ja';
        else currentLang = 'en';
    }
    updateLangUI(currentLang);
}

function changeLanguage(lang) {
    if (!translations[lang]) return;
    currentLang = lang;
    localStorage.setItem('caddy_stats_lang', lang);
    updateLangUI(lang);
    applyTranslations();
    updateDashboardValues(); 
}

function updateLangUI(lang) {
    document.documentElement.lang = lang;
    document.getElementById('currentLangLabel').innerText = langLabels[lang] || lang;
    document.querySelectorAll('.lang-option').forEach(opt => {
        opt.classList.remove('selected');
        if(opt.getAttribute('onclick').includes(lang)) opt.classList.add('selected');
    });
}

function applyTranslations() {
    const t = translations[currentLang];
    document.title = t.page_title;
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (t[key]) el.innerText = t[key];
    });
}

window.addEventListener('DOMContentLoaded', initDashboard);